### ISSUE TITLE
When is it time to reformat the code? 

### ISSUE THREAD

**Issue by ckuethe** [brandon-rhodes/python-sgp4#19] opened 2017-08-22 13:46 UTC
The reference implementation of sgp4 hasn't changed significantly in a decade. It should be pretty straightforward (if tedious) to reimplement future changes in python, especially if they provide test cases.

To that end, I'm starting to rename variables but we should probably have a discussion about when to pep8 the code. 

https://github.com/ckuethe/python-sgp4/commits/more_pythonic

**Comment by brandon-rhodes** [comment] 2017-08-23 01:14
My tendency would be to start morphing the code only as we need to touch it for other reasons. One possible reason would be to eliminate the awkward way that we have to call routines with dozens of values all in a tuple — fixing that cleanly would involve touching lots of code that could be cleaned up.

But I'm not sure we should rename any variables, because it would make it very difficult to compare the code with other reference implementations, wouldn't it?

**Comment by ckuethe** [comment] 2017-08-23 01:36
I wouldn't say "very difficult", just a little bit tedious. But less tedious than wondering what `method = 'd'` does. Diff the upstream C sources and translate to python. If you look at what changed when the "improved" mode arrived (compared to "afspc" mode) the change is pretty small.

In my head, having a pure-python implementation of implies being programmer friendly and pythonic rather than just prepending an appropriate number of spaces to every line. Otherwise, why not just use a python binding to libastro?

**Comment by brandon-rhodes** [comment] 2017-08-23 01:54
The Python binding to libastro requires someone compiling the library under Windows, which proved a huge problem with PyEphem — so the main point of this SGP4 module was not to try to rewrite all the already-working code to follow different idioms, but to make the minimum number of changes necessary so that it could run under Python. I was not really planning on us spending time in the code, as I suspect it should stay identical in function to the reference SGP4 implementation?

I had supposed that these tweaks we are making to fix Numba compatibility, along with whatever other tweaks we might need to get high performance, would be the last times we would touch the library — once it's a performant port of the original code, I think we can call it done and move back to building on it further in Skyfield? (Which *IS* where I wanted to make everything beautiful and Pythonic!)

**Comment by ckuethe** [comment] 2017-08-23 05:25
So a black box, optionally accelerated by another black box if you happen to have numba available? And people should don their eclipse goggles and welding masks before attempting to gaze upon the SGP4 code?

**Comment by brandon-rhodes** [comment] 2017-08-23 11:14
Not a black box, but a box that would not be under active development, and so could be usefully kept quite close to its source material. I hadn't imagined anyone doing active development on the Python code — if the SGP4 algorithm is ever improved or expanded or tweaked, I had imagined that the improvement would happen on a team that used C or FORTRAN code, and then the result would be passed downstream back to this version of the code. In which case, the closer this code stays to the original, the easier it will be to identify and make the change, I'd thought?

But, again, there are ugly things about the code that it would be great to fix — like the huge tuples being passed back and forth — and I have no objection to tweaking code that has to be touched anyway in the course of meeting other goals!

**Comment by ckuethe** [comment] 2017-08-23 19:12
I think we're converging on an understanding.

The argument that it would be easier to integrate future changes by preserving the terrible format does not hold much water for me. The [code itself](https://github.com/brandon-rhodes/python-sgp4/blob/master/sgp4/propagation.py#L59) shows how little it's been changed once they got it working properly. Others ([such as dnwnr](https://github.com/dnwrnr/sgp4/blob/master/libsgp4/SGP4.cpp)) do not seem to have difficulties maintaining the code with nice variable names, and it's much easier to read. And legible code will be easier to patch if a new version comes out in 5 years.

Using the [wayback machine](https://web.archive.org/web/*/celestrak.com/software/vallado/cpp.zip), I diffed the last few versions of the [standalone c++](http://celestrak.com/software/vallado-sw.asp) code with the following findings, and the actual algorithmic diff isn't that big. Unfortunately the file structure has been rearranged which invalidates attempts at making it easy to integrate changes.

As for passing tuples around, I think we do need to keep doing that so numba knows all the [numpy types](http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html). We can't pass in objects otherwise it falls back to nopython mode which isn't very fast.

**Comment by brandon-rhodes** [comment] 2019-08-19 20:35
Pull request #35 suggests that it’s still convenient that this module’s code still looks a good bit like the C++ code it was derived from. Should we close this issue and decide to keep the similarity around as 
a feature for the near future?

**Comment by ckuethe** [comment] 2019-08-20 04:48
Yeah, I think we can close this for now. Opening issues is cheap and easy, and we can revisit it after cythonizing everything.

That said, the wayback machine will give you zip files for ...

* cpp-20030701.zip
* cpp-20090504.zip
* cpp-20130806.zip
* cpp-20160523.zip
* cpp-20180418.zip

Well, they're all called cpp.zip, and I renamed them based on the most recent file present in each archive. Over time, the code structure has changed, so diffing algorithm changes isn't exactly trivial. 
Zips are here for the next week or so... https://drive.google.com/open?id=1L_PFk6dUDk4G5fPMoMb7C1CBbDTwX1P0

**Comment by interplanetarychris** [comment] 2019-10-13 19:54
FYI, I confirmed that the contents of the zip file "cpp-20180418.zip" above are the same as the version I prepared PR #35 from (despite the earlier date, which was cited in the change log in the code).

**Comment by brandon-rhodes** [comment] 2019-10-14 03:12
Thanks for the update! I'll go ahead and close this, moving attention to the other open issues on the subject.

**Closed by brandon-rhodes** 2019-10-14 03:12 UTC
