### ISSUE TITLE
Insensitivity to Inclination, RAAN

### ISSUE THREAD

**Issue by dcajacob** [brandon-rhodes/python-sgp4#12] opened 2016-01-13 05:12 UTC
TLEs that only differ in inclination or RAAN of very small angles (~0.001 degrees or less) when propagated using SGP4 seem to yield identical positions.  Inclination or RAAN has to be adjusted to  greater degree to yield a change.  Seems like there's some loss of precision somewhere...

Will add example code to recreate error tomorrow.

**Comment by brandon-rhodes** [comment] 2016-01-17 23:52
That is an unexpected result! I would have thought that a small difference in inclination would yield a small difference in position. Yes, please do post an example as soon as you can get one together and we can take a look!

**Comment by brandon-rhodes** [comment] 2016-06-09 23:45
I am going to close this issue temporarily, to keep it off of my GitHub dashboard until there is enough information for me to reproduce the problem. Simply re-open the issue once you have the example code you are planning on providing. Thanks!

**Closed by brandon-rhodes** 2016-06-09 23:45 UTC

**Comment by ckuethe** [comment] 2016-10-04 04:41
Maybe I'm doing it wrong, but I can't reproduce this.

![screenshot_2016-10-03_21-40-11](https://cloud.githubusercontent.com/assets/1131751/19062805/007f016a-89b2-11e6-84d7-892ee8453a56.png)


[sgp4bug12.py.txt](https://github.com/brandon-rhodes/python-sgp4/files/507697/sgp4bug12.py.txt)
